### ISSUE TITLE
[HOS-10] Definir ambiente de produção e testá-lo

### ISSUE THREAD

**Issue by caioreius** [celso-patiri/hostel-app-gcva#10]
## Descrição

Eu como Desenvolvedor, quero definir um ambiente de produção afim de hospedar minha aplicação e disponibilizá-la para os stakeholder's 

## Tasks

- [ ] Definir o ambiente de produção (Heroku, Amazon Web Services, Azure, Google Cloud, Alibaba, etc);
- [ ] Fazer o deployment de uma aplicação inicial do tipo "Hello World" neste ambiente de produção escolhido.

## Quem completou:

- [ ] Caio
- [ ] Guilherme
- [ ] Celso
- [ ] João
- [ ] Arthur
- [ ] Rafael
- [ ] André
- [ ] Gabriel

**Comment by GuilhermeAGouveia** [comment]
Ambiente escolhido: AWS ECS
