### ISSUE TITLE
[HOS-0] Definir ferramenta de build

### ISSUE THREAD

**Issue by caioreius** [celso-patiri/hostel-app-gcva#2]
## Descrição

Eu como Membro do time Scrum, quero definir uma ferramenta de build para trabalhar com pacotes centralizados e de fácil gerenciamento.

## Tasks

- [x] Chegar em consenso com o grupo de desenvolvedores sobre qual plataforma usar para gerenciamento do projeto;
- [x] Compatibilidade com JDK 8, JDK que os servidores de aplicação suportam.

## Quem completou:

- [x] Caio
- [ ] Guilherme
- [x] Celso
- [ ] João
- [ ] Arthur
- [x] Rafael
- [ ] André
- [ ] Gabriel

**Comment by GuilhermeAGouveia** [comment]
Escolhido: Maven
